### PR TITLE
Feature: upgrades psql from 9 to 11

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The container logs are not promising:
```
elife@pr-9-base-update-adhoc3--digests:~$ docker logs -f digests_wsgi_1
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'auth_group'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_group_permissions'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_permission'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_user'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_user_groups'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'auth_user_user_permissions'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'digests_digest'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_admin_log'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_content_type'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_migrations'
# The error was: sequence index must be integer, not 'slice'
# Unable to inspect table 'django_session'
# The error was: sequence index must be integer, not 'slice'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, digests, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
[uWSGI] getting INI configuration from /srv/digests/uwsgi.ini
```
But the container becomes eventually `healthy`.

**Comment by giorgiosironi** [comment]
Still can't reproduce by running the same commands in a sequence on a new stack, but the errors I posted are still there.
Would re-run also after `builder-configuration` is merged, because current pillars in there make all the builds use Postgres 9 rather than 11.

**Comment by lsh-0** [comment]
I can see the same errors in adhoc2 instance. debugging from there

**Comment by lsh-0** [comment]
alrighty, this is looking healthier (I guess?):

```
$ docker logs bcaa974aaf31
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DigestsDigest(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    content = models.TextField()  # This field type is a guess.
    image = models.TextField()  # This field type is a guess.
    impactstatement = models.TextField(db_column='impactStatement', blank=True, null=True)  # Field name made lowercase.
    published = models.DateTimeField(blank=True, null=True)
    relatedcontent = models.TextField(db_column='relatedContent')  # Field name made lowercase. This field type is a guess.
    stage = models.CharField(max_length=25)
    subjects = models.TextField(blank=True, null=True)  # This field type is a guess.
    title = models.CharField(max_length=255)
    updated = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'digests_digest'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, digests, sessions
Running migrations:
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
[uWSGI] getting INI configuration from /srv/digests/uwsgi.ini
elife@pr-9-base-update-adhoc2--digests:~/digests$
```

kicking builds

**Comment by lsh-0** [comment]
build kicks back:

```haskell
[2019-10-18T00:45:10.270Z] [localhost] local: ssh -o "StrictHostKeyChecking no" ubuntu@3.95.63.60 "exit"
[2019-10-18T00:45:10.270Z] [54.91.91.160] Executing task 'single_node_work'
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport - Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport - Traceback (most recent call last):
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport -   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1893, in run
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport -     self._check_banner()
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport -   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/paramiko/transport.py", line 2049, in _check_banner
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport -     'Error reading SSH protocol banner' + str(e)
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport - SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
[2019-10-18T00:45:10.270Z] ERROR - paramiko.transport - 
[2019-10-18T00:45:10.521Z] ERROR - buildercore.core - Needed to prompt for a connection or sudo password (host: 54.91.91.160), but input would be ambiguous in parallel mode
[2019-10-18T00:45:10.521Z] !!! Parallel execution exception under host '54.91.91.160':
[2019-10-18T00:45:10.521Z] Process 54.91.91.160:
[2019-10-18T00:45:10.521Z] Traceback (most recent call last):
[2019-10-18T00:45:10.521Z]   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2019-10-18T00:45:10.521Z]     self.run()
[2019-10-18T00:45:10.521Z]   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
[2019-10-18T00:45:10.521Z]     self._target(*self._args, **self._kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 241, in inner
[2019-10-18T00:45:10.521Z]     submit(task.run(*args, **kwargs))
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
[2019-10-18T00:45:10.521Z]     return self.wrapped(*args, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/decorators.py", line 185, in inner
[2019-10-18T00:45:10.521Z]     return func(*args, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/core.py", line 335, in single_node_work
[2019-10-18T00:45:10.521Z]     raise err
[2019-10-18T00:45:10.521Z] FabricException: Needed to prompt for a connection or sudo password (host: 54.91.91.160), but input would be ambiguous in parallel mode
[2019-10-18T00:45:10.521Z] Traceback (most recent call last):
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/main.py", line 757, in main
[2019-10-18T00:45:10.521Z]     *args, **kwargs
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
[2019-10-18T00:45:10.521Z]     results['<local-only>'] = task.run(*args, **new_kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
[2019-10-18T00:45:10.521Z]     return self.wrapped(*args, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/decorators.py", line 58, in wrap2
[2019-10-18T00:45:10.521Z]     return func(pname, *args, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/masterless.py", line 22, in wrapper
[2019-10-18T00:45:10.521Z]     return fn(*args, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/masterless.py", line 104, in launch
[2019-10-18T00:45:10.521Z]     bootstrap.create_stack(stackname)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/bootstrap.py", line 79, in create_stack
[2019-10-18T00:45:10.521Z]     setup_ec2(stackname, context)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/context_handler.py", line 84, in decorated_with_only_if
[2019-10-18T00:45:10.521Z]     return fn(stackname, context, **kwargs)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/bootstrap.py", line 106, in setup_ec2
[2019-10-18T00:45:10.521Z]     stack_all_ec2_nodes(stackname, _setup_ec2_node, username=BOOTSTRAP_USER)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/core.py", line 348, in stack_all_ec2_nodes
[2019-10-18T00:45:10.521Z]     return parallel_work(single_node_work, params)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/src/buildercore/core.py", line 361, in parallel_work
[2019-10-18T00:45:10.521Z]     return execute(parallel(single_node_work), hosts=list(params['public_ips'].values()))
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 418, in execute
[2019-10-18T00:45:10.521Z]     error(err, exception=d['results'])
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/utils.py", line 358, in error
[2019-10-18T00:45:10.521Z]     return func(message)
[2019-10-18T00:45:10.521Z]   File "/ext/srv/builder/venv/local/lib/python2.7/site-packages/fabric/utils.py", line 54, in abort
[2019-10-18T00:45:10.521Z]     raise env.abort_exception(msg)
[2019-10-18T00:45:10.521Z] buildercore.config.FabricException: One or more hosts failed while executing task 'single_node_work'
```

**Comment by lsh-0** [comment]
nope, same error

**Comment by lsh-0** [comment]
everything was upgraded without a hitch.

kicking build one last time

**Comment by lsh-0** [comment]
Problem appears to be in base formula: https://github.com/elifesciences/digests-formula/pull/10

And nothing to do with this PR. Doesn't mean I broke it somehow ;) Just not with this PR.

**Pull request merged**
